### ISSUE TITLE
Downloaders are not supported.

### ISSUE THREAD

**Issue by Nigward8174** [ch2sh/Crybat#12]
I used Unam's Downloader and it seems it's not working at all. I added windows defender exclusions, the file to be downloaded, and message of downloader itself. I tried both Native and .NET (menaged) and none of it seemed to work.

**Comment by ch2sh** [comment]
Downloaders are very much supported. This is either an error within your downloader or lack of permissions. Remember, you're adding Windows Defender exclusions, you need admin permissions.

**Comment by Nigward8174** [comment]
Yeah, and Im running bat as admin

**Comment by Nigward8174** [comment]
Downloader itself works (before turning it to .bat) 
I did fake error so I can see if downloader even started. 
After downloader (as .bat) is launched, it creates a process (in process hacker) and kills it quite fast. No message ever appears.

**Comment by Nigward8174** [comment]
Also I tried changing it to native instead of .net and it seems that WD detects it as wacatac
![image](https://user-images.githubusercontent.com/96837088/182551695-ba973794-461e-4d26-92f2-2a5376e1b39e.png)

Not the bat itself, but the downloader in the bat

**Comment by Nigward8174** [comment]
Is there any way to like disable AVs and stuff, and then start the file in .bat
